Make pandas a dev requirement

diff --git a/.github/workflows/lint-and-test.yml b/.github/workflows/lint-and-test.yml
--- a/.github/workflows/lint-and-test.yml
+++ b/.github/workflows/lint-and-test.yml
@@ -5,6 +5,7 @@ on:
   push:
     branches:
       - master
+      - update/onnx-usage
 
 jobs:
   lint-and-test:
@@ -59,5 +60,15 @@ jobs:
           output=$(curl --retry-all-errors --retry 3 -sS http://localhost:8000/)
           if [[ "$output" != '"Hello!"' ]]; then
             echo "Test failed. Output is: $output"
+            exit 1
+          fi
+
+      # Checking for the probability of the top result on a known image.
+      - name: Check prediction works
+        run: |
+          full_response=$(curl -sS -X POST -F "img_file=@tests/pterois-volitans.jpg" http://localhost:8000/predict | jq)
+          jq_check_result=$(echo "$full_response" | jq '.["Pterois volitans"] > 0.85')
+          if [[ "$jq_check_result" != 'true' ]]; then
+            echo "Test failed. Check result: $jq_check_result\nFull response:\n$full_response"
             exit 1
           fi
