Test docker build in GHA

diff --git a/.github/workflows/lint-and-test.yml b/.github/workflows/lint-and-test.yml
--- a/.github/workflows/lint-and-test.yml
+++ b/.github/workflows/lint-and-test.yml
@@ -5,6 +5,7 @@ on:
   push:
     branches:
       - master
+      - try/onnx-export
 
 jobs:
   lint-and-test:
@@ -34,3 +35,26 @@ jobs:
 
       - name: Run tests
         run: poetry run pytest
+
+  test-docker-api:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repo
+        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # pin@v3.5.2
+
+      - name: Build API Docker image
+        run: docker build -t ichthywhat .
+
+      - name: List images
+        run: docker images
+
+      - name: Run API Docker container
+        run: docker run -d --env UVICORN_HOST=0.0.0.0 -p 127.0.0.1:8000:8000 ichthywhat:latest
+
+      - name: Check container health
+        run: |
+          output=$(curl --retry 3 -sS http://localhost:8000/)
+          if [[ "$output" != '"Hello!"' ]]; then
+            echo "Test failed. Output is: $output"
+            exit 1
+          fi
